#!/bin/bash

# grids
case=10


# case
cp -rf 2D case2D
cd case2D
chmod +x clean
chmod +x run
sed -i "s/cells.*[0-9][0-9]*;/cells $case;/g" system/blockMeshDict
./clean
sbatch run
cd ..


# case_alt
cp -rf 2D_alt case2D_alt
cd case2D_alt
chmod +x clean
chmod +x run
sed -i "s/cells.*[0-9][0-9]*;/cells $case;/g" system/blockMeshDict
./clean
sbatch run
cd ..
