#!/bin/bash

# grids
case=10


# case
cp -rf 3D case3D
cd case3D
chmod +x clean
chmod +x run
sed -i "s/cells.*[0-9][0-9]*;/cells $case;/g" system/blockMeshDict
./clean
sbatch run
cd ..


# case_alt
cp -rf 3D_alt case3D_alt
cd case3D_alt
chmod +x clean
chmod +x run
sed -i "s/cells.*[0-9][0-9]*;/cells $case;/g" system/blockMeshDict
./clean
sbatch run
cd ..
