#!/bin/bash

# grids
coarse=90
medium=120
fine=160


# coarse
cp -rf 2D coarse2D
cd coarse2D
chmod +x clean
chmod +x run
sed -i "s/cells.*[0-9][0-9]*;/cells $coarse;/g" system/blockMeshDict
./clean
sbatch run
cd ..


# medium
cp -rf 2D medium2D
cd medium2D
chmod +x clean
chmod +x run
sed -i "s/cells.*[0-9][0-9]*;/cells $medium;/g" system/blockMeshDict
./clean
sbatch run
cd ..


# fine
cp -rf 2D fine2D
cd fine2D
chmod +x clean
chmod +x run
sed -i "s/cells.*[0-9][0-9]*;/cells $fine;/g" system/blockMeshDict
./clean
sbatch run
cd ..
