#!/bin/bash

# grids
cells=5
ogridCells=10
firstCell=0.00064
refine=1
urefine=1
hRef=1
lRef=1


# LES
cd STD
cp -rf 3D 3D_LES
cd 3D_LES
chmod +x clean
chmod +x run
sed -i "s/cells.*[0-9][0-9]*;/cells $cells;/g" system/blockMeshDict
sed -i "s/ogridCells.*[0-9][0-9]*;/ogridCells $ogridCells;/g" system/blockMeshDict
sed -i "s/firstCell.*[0-9][0-9]*;/firstCell $firstCell;/g" system/blockMeshDict
sed -i "s/refine.*[0-9][0-9]*;/refine $refine;/g" system/blockMeshDict
sed -i "s/urefine.*[0-9][0-9]*;/urefine $urefine;/g" system/blockMeshDict
sed -i "s/hRef.*[0-9][0-9]*;/hRef $hRef;/g" system/blockMeshDict
sed -i "s/lRef.*[0-9][0-9]*;/lRef $lRef;/g" system/blockMeshDict
sed -i "s/nutFunction/nutUSpaldingWallFunction/g" 0.orig/nut
sed -i "s/nutValue/\$internalField/g" 0.orig/nut
./clean
sbatch run
cd ..
cd ..
