#!/bin/bash

# grids
case=20


# case
cp -rf 2D case2D
cd case2D
chmod +x clean
chmod +x run
sed -i "s/cells.*[0-9][0-9]*;/cells $case;/g" system/blockMeshDict
sed -i "s/const scalar cellDistribution =.*[0-9][0-9]*;/const scalar cellDistribution = $case;/g" system/criteria
sed -i "s/kFunction/kqRWallFunction/g" 0.orig/k
sed -i "s/kValue/\$internalField/g" 0.orig/k
sed -i "s/nutFunction/nutkWallFunction/g" 0.orig/nut
sed -i "s/nutValue/\$internalField/g" 0.orig/nut
./clean
sbatch run
cd ..
