#!/bin/bash

# grids
coarse=12
medium=18
fine=27


# coarse
cp -rf 3D coarse3D
cd coarse3D
chmod +x clean
chmod +x run
sed -i "s/cells.*[0-9][0-9]*;/cells $coarse;/g" system/blockMeshDict
./clean
sbatch run
cd ..


# medium
cp -rf 3D medium3D
cd medium3D
chmod +x clean
chmod +x run
sed -i "s/cells.*[0-9][0-9]*;/cells $medium;/g" system/blockMeshDict
./clean
sbatch run
cd ..


# fine
cp -rf 3D fine3D
cd fine3D
chmod +x clean
chmod +x run
sed -i "s/cells.*[0-9][0-9]*;/cells $fine;/g" system/blockMeshDict
./clean
sbatch run
cd ..
